from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE_ROOT = ROOT / "src" if (ROOT / "src").exists() else ROOT
OUT = ROOT / "analysis" / "runtime_resource_audit" / "runtime_resource_audit.md"

RUNTIME_FILES = [
    SOURCE_ROOT / "EchoPet.ino",
    SOURCE_ROOT / "EchoPetDisplay.cpp",
    SOURCE_ROOT / "EchoPetDisplay.h",
    SOURCE_ROOT / "EchoPetMenuIconResources.cpp",
    SOURCE_ROOT / "EchoPetMenuIconResources.h",
    SOURCE_ROOT / "EchoPetSprites.cpp",
    SOURCE_ROOT / "EchoPetSprites.h",
    SOURCE_ROOT / "EchoPetCatalogVisuals.cpp",
    SOURCE_ROOT / "EchoPetCatalogVisuals.h",
    SOURCE_ROOT / "EchoPetCharacterVisuals.cpp",
    SOURCE_ROOT / "EchoPetCharacterVisuals.h",
    SOURCE_ROOT / "EchoPetResources64.cpp",
    SOURCE_ROOT / "EchoPetResources64.h",
    SOURCE_ROOT / "EchoPetResources128.cpp",
    SOURCE_ROOT / "EchoPetResources128.h",
    SOURCE_ROOT / "EchoPetModel.cpp",
    SOURCE_ROOT / "EchoPetModel.h",
    SOURCE_ROOT / "EchoPetCatalog.cpp",
    SOURCE_ROOT / "EchoPetCatalog.h",
]

RASTER_EXTENSIONS = (".png", ".jpg", ".jpeg", ".gif", ".bmp")
FORBIDDEN_FILENAME_RE = re.compile(
    r"['\"][^'\"]+\.(?:png|jpg|jpeg|gif|bmp)['\"]", re.IGNORECASE
)
FORBIDDEN_FILE_LOAD_RE = re.compile(
    r"\b(?:LittleFS|InternalFS|SD)\s*\.\s*open\s*\(|\bopen\s*\(",
    re.IGNORECASE,
)


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def runtime_pattern_hits() -> list[tuple[str, int, str]]:
    hits: list[tuple[str, int, str]] = []
    for path in RUNTIME_FILES:
        text = read(path)
        for number, line in enumerate(text.splitlines(), start=1):
            if (FORBIDDEN_FILENAME_RE.search(line) or
                    FORBIDDEN_FILE_LOAD_RE.search(line)):
                hits.append((path.name, number, line.strip()))
    return hits


def raster_files() -> list[Path]:
    return sorted(
        path for path in ROOT.rglob("*")
        if path.is_file() and path.suffix.lower() in RASTER_EXTENSIONS
    )


def is_analysis_artifact(path: Path) -> bool:
    try:
        rel = path.relative_to(ROOT)
    except ValueError:
        return False
    return rel.parts and rel.parts[0] == "analysis"


def source_has_bitmap_arrays() -> bool:
    sprites = read(SOURCE_ROOT / "EchoPetSprites.cpp")
    catalog_visuals = read(SOURCE_ROOT / "EchoPetCatalogVisuals.cpp")
    character_visuals = read(SOURCE_ROOT / "EchoPetCharacterVisuals.cpp")
    icon_resources = read(SOURCE_ROOT / "EchoPetMenuIconResources.cpp")
    display = read(SOURCE_ROOT / "EchoPetDisplay.cpp")
    return (
        "const uint8_t kEggBodyBitmap[] PROGMEM" in sprites
        and "const FramePart kFrameEgg0Parts[] PROGMEM" in sprites
        and "const ComposedFrame kFrameEgg0Composed" in sprites
        and "const ComposedFrame* connectFrame(SpriteFrame frame)" in sprites
        and "const uint16_t kFoodRiceBall[16] PROGMEM" in catalog_visuals
        and "const uint16_t kItemBox[16] PROGMEM" in catalog_visuals
        and "const uint16_t kSouvenirBase[16] PROGMEM" in catalog_visuals
        and "kSouvenirMemoryBitmaps[kCatalogSouvenirMemoryVisualCount]" in catalog_visuals
        and "const uint16_t kCharacterMame[16] PROGMEM" in character_visuals
        and "kCharacterCatalogBitmaps[kCharacterVisualCatalogCount]" in character_visuals
        and "kCharacterIdleBitmaps[kCharacterVisualCatalogCount]" in character_visuals
        and "void drawCharacterFamilyBitmap" in character_visuals
        and "void drawCharacterCatalogBitmap" in character_visuals
        and "void drawCharacterCatalogIdleBitmap" in character_visuals
        and "kEchoPetMenuIconSemantics" in icon_resources
        and "kEchoPetMenuIcons128Large[kEchoPetMenuIconCount]" in icon_resources
        and "kEchoPetMenuIcons64Compact[kEchoPetMenuIconCount]" in icon_resources
        and "Connection/Communication" in icon_resources
        and "drawPackedBitmap(display, kEchoPetMenuIcons64Compact[i], 12, 12"
        in display
        and "drawPackedBitmap(display, kEchoPetMenuIcons128Large[i], 30, 30"
        in display
    )


def main() -> None:
    rasters = raster_files()
    runtime_rasters = [path for path in rasters if not is_analysis_artifact(path)]
    hits = runtime_pattern_hits()
    bitmap_arrays = source_has_bitmap_arrays()

    status = "PASS" if not runtime_rasters and not hits and bitmap_arrays else "FAIL"

    lines = [
        "# EchoPet Runtime Resource Audit",
        "",
        "Generated by `analysis/runtime_resource_audit/generate_runtime_resource_audit.py`.",
        "",
        "This audit checks the firmware resource route. Runtime animation and",
        "icon resources must be C/C++ bitmap arrays and composed frame tables,",
        "not PNG/JPG/GIF/BMP files.",
        "",
        "## Summary",
        "",
        f"- Overall status: `{status}`.",
        f"- Runtime raster files outside `analysis/`: `{len(runtime_rasters)}`.",
        f"- Forbidden runtime image/file-load pattern hits: `{len(hits)}`.",
        f"- C/C++ bitmap/composed-frame evidence present: `{'yes' if bitmap_arrays else 'no'}`.",
        f"- Analysis-only raster artifacts: `{len(rasters) - len(runtime_rasters)}`.",
        "",
        "## Runtime Resource Evidence",
        "",
        "- `EchoPetSprites.cpp` contains `PROGMEM` bitmap assets and `FramePart` composed frames.",
        "- `EchoPetCatalogVisuals.cpp` contains `PROGMEM` catalog food/item/souvenir fallback rows and per-memory souvenir bitmap rows.",
        "- `EchoPetCharacterVisuals.cpp` contains `PROGMEM` character-family fallback rows plus per-catalog 16x16 portrait and 24x24 idle bitmap rows.",
        "- `EchoPetResources64.cpp` and `EchoPetResources128.cpp` contain screen layout resources.",
        "- `EchoPetMenuIconResources.cpp` contains the fixed-menu semantic table plus 12x12 and 30x30 C/C++ byte arrays.",
        "- `EchoPetDisplay.cpp` selects the 12x12 or 30x30 fixed menu icon source by layout while preserving the same menu action order.",
        "- Runtime source does not reference external raster filenames or file-load APIs.",
        "",
        "## Runtime Raster Files Outside Analysis",
        "",
    ]
    if runtime_rasters:
        lines.extend(f"- `{path.relative_to(ROOT)}`" for path in runtime_rasters)
    else:
        lines.append("- none")

    lines += [
        "",
        "## Forbidden Runtime Pattern Hits",
        "",
    ]
    if hits:
        lines.extend(
            f"- `{file}:{line}` `{text}`" for file, line, text in hits
        )
    else:
        lines.append("- none")

    lines += [
        "",
        "## Analysis-Only Raster Artifacts",
        "",
    ]
    analysis_rasters = [path for path in rasters if is_analysis_artifact(path)]
    if analysis_rasters:
        lines.extend(f"- `{path.relative_to(ROOT)}`" for path in analysis_rasters)
    else:
        lines.append("- none")

    lines += [
        "",
        "## Contract Boundary",
        "",
        "- Files listed under analysis are proof artifacts only.",
        "- They are not firmware resources and must not be loaded by runtime code.",
        "- Future pet replacements should edit C/C++ bitmap arrays and composed frame definitions.",
    ]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    if status != "PASS":
        raise SystemExit(1)


if __name__ == "__main__":
    main()

