#pragma once

#include <stdint.h>

#if defined(ECHOPET_TARGET_GAT562) && ECHOPET_TARGET_GAT562

#define ECHOPET_TARGET_NAME "GAT562 Mesh EVB Pro"

#define ECHOPET_TARGET_DISPLAY_EPD 0
#define ECHOPET_TARGET_DISPLAY_SSD1306 1

#ifndef SCREEN_WIDTH
#define SCREEN_WIDTH 128
#endif
#ifndef SCREEN_HEIGHT
#define SCREEN_HEIGHT 64
#endif

#define ECHOPET_OLED_I2C_SDA 13
#define ECHOPET_OLED_I2C_SCL 14
#define ECHOPET_OLED_I2C_ADDRESS 0x3C

#define ECHOPET_PERIPHERAL_POWER_EN 34
#define ECHOPET_STATUS_LED 35
#define ECHOPET_STATUS_LED_ACTIVE_HIGH 1

// Tamagotchi-style three-key projection on the GAT562 joystick.
#define ECHOPET_BUTTON_A_PIN 30  // Left: select.
#define ECHOPET_BUTTON_B_PIN 28  // Up: confirm.
#define ECHOPET_BUTTON_C_PIN 31  // Right: cancel.
#define ECHOPET_BUTTON_A_FALLBACK_PIN 9
#define ECHOPET_BUTTON_B_FALLBACK_PIN 12
#define ECHOPET_BUTTON_ACTIVE_LOW 1
#define ECHOPET_BUTTON_NEED_PULLUP 1
#define ECHOPET_BUTTON_DEBOUNCE_MS 50
#define ECHOPET_HAS_KEYSIELD 0

#define ECHOPET_LORA_CS 42
#define ECHOPET_LORA_DIO1 47
#define ECHOPET_LORA_RST 38
#define ECHOPET_LORA_BUSY 46
#define ECHOPET_LORA_SCLK 43
#define ECHOPET_LORA_MOSI 44
#define ECHOPET_LORA_MISO 45
#define ECHOPET_LORA_POWER_EN 37
#define ECHOPET_LORA_HAS_MANUAL_RF_SWITCH 0
#define ECHOPET_LORA_RF_SWITCH_TX -1
#define ECHOPET_LORA_RF_SWITCH_RX -1
#define ECHOPET_LORA_TCXO_VOLTAGE 1.8f
#define ECHOPET_LORA_OUTPUT_POWER_DBM 22

#else

#include "t_echo_lite_config.h"

#define ECHOPET_TARGET_NAME "T-Echo-Lite"

#define ECHOPET_TARGET_DISPLAY_EPD 1
#define ECHOPET_TARGET_DISPLAY_SSD1306 0

#define ECHOPET_PERIPHERAL_POWER_EN RT9080_EN
#define ECHOPET_STATUS_LED LED_1
#define ECHOPET_STATUS_LED_ACTIVE_HIGH 1

#define ECHOPET_KEYSIELD_I2C_SDA IIC_1_SDA
#define ECHOPET_KEYSIELD_I2C_SCL IIC_1_SCL
#define ECHOPET_KEYSIELD_INT EXT_2X5P_1_IO_1_3
#define ECHOPET_BOOT_BUTTON_PIN nRF52840_BOOT
#define ECHOPET_HAS_KEYSIELD 1

#define ECHOPET_LORA_CS SX1262_CS
#define ECHOPET_LORA_DIO1 SX1262_DIO1
#define ECHOPET_LORA_RST SX1262_RST
#define ECHOPET_LORA_BUSY SX1262_BUSY
#define ECHOPET_LORA_SCLK SX1262_SCLK
#define ECHOPET_LORA_MOSI SX1262_MOSI
#define ECHOPET_LORA_MISO SX1262_MISO
#define ECHOPET_LORA_POWER_EN -1
#define ECHOPET_LORA_HAS_MANUAL_RF_SWITCH 1
#define ECHOPET_LORA_RF_SWITCH_TX SX1262_RF_VC1
#define ECHOPET_LORA_RF_SWITCH_RX SX1262_RF_VC2
#define ECHOPET_LORA_TCXO_VOLTAGE 1.6f
#define ECHOPET_LORA_OUTPUT_POWER_DBM 22

#endif
